server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    # url rewrite 문제 해결
    session:
      tracking-modes: cookie
  port: 5000

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ropatestdb
#    username: ropa
#    password: ropa1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOST}:3306/ropadb
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: INFO
    shop.mtcoding.blog: DEBUG